title: "Anantha Rao"
email: anantha1996sn@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "/" 
twitter_username: mlhacks
github_username:  AnanthaSNRao

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
